// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeniorDesignFall2024.Database.Model.OpenHab.Context;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(SdDbContext))]
    partial class SdDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SeniorDesignFall2024.Database.Model.OpenHab.Entity.Item", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("StateId")
                        .HasColumnType("integer");

                    b.HasKey("Uid");

                    b.HasIndex("StateId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("SeniorDesignFall2024.Database.Model.OpenHab.Entity.StateType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "displayState");

                    b.Property<string>("ParentItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "state");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.HasIndex("ParentItemId");

                    b.ToTable("StateType");

                    b.HasDiscriminator<string>("type").HasValue("object");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SeniorDesignFall2024.Database.Model.OpenHab.Entity.DecimalType", b =>
                {
                    b.HasBaseType("SeniorDesignFall2024.Database.Model.OpenHab.Entity.StateType");

                    b.Property<decimal>("NumericState")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "numericState");

                    b.HasDiscriminator().HasValue("Decimal");
                });

            modelBuilder.Entity("SeniorDesignFall2024.Database.Model.OpenHab.Entity.QuantityType", b =>
                {
                    b.HasBaseType("SeniorDesignFall2024.Database.Model.OpenHab.Entity.DecimalType");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "unit");

                    b.HasDiscriminator().HasValue("Quantity");
                });

            modelBuilder.Entity("SeniorDesignFall2024.Database.Model.OpenHab.Entity.Item", b =>
                {
                    b.HasOne("SeniorDesignFall2024.Database.Model.OpenHab.Entity.StateType", "State")
                        .WithMany()
                        .HasForeignKey("StateId");

                    b.Navigation("State");
                });

            modelBuilder.Entity("SeniorDesignFall2024.Database.Model.OpenHab.Entity.StateType", b =>
                {
                    b.HasOne("SeniorDesignFall2024.Database.Model.OpenHab.Entity.Item", "ParentItem")
                        .WithMany("AllStateData")
                        .HasForeignKey("ParentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentItem");
                });

            modelBuilder.Entity("SeniorDesignFall2024.Database.Model.OpenHab.Entity.Item", b =>
                {
                    b.Navigation("AllStateData");
                });
#pragma warning restore 612, 618
        }
    }
}
